### ISSUE TITLE
Feedback for Rev1

### ISSUE THREAD

**Issue by leedotpang** [Spiggles8/Rock_Paper_Scissors#1]
I'm not familiar with the ins and outs of the PyQT library are, but your code is clean, readable, well commented, and seems to make sense given the challenge and your solution. 

I feel like we can refactor this project a bit and maybe you can use it to level-up your best-practices. Otherwise, if you just keep making new projects, that will help as well.

I'll focus on two areas, since it looks like you have a lot of basics down already:

1. ### The first cases are if the results are equal then it is a tie.
https://github.com/Spiggles8/Rock_Paper_Scissors/blob/573d62f2be84e17670908f4f66695cdc4ff849c9/RockPaperScissors_rev1.0.py#L151-L160

If you look closely, you'll see that for the logical flow, you're checking to see if both the *users input* and the *computers input* are the same. Logically, that can be represented by just checking to see if `user_Input ==  computer_Input`. Try refactoring that section of the code and let me know where that takes you.

2. ### Winning cases
https://github.com/Spiggles8/Rock_Paper_Scissors/blob/573d62f2be84e17670908f4f66695cdc4ff849c9/RockPaperScissors_rev1.0.py#L162-L182

This section is harder to provide a specific suggestion for, since it's the heart and soul of the winning logic. The main thing to point out though is that your logic is repeated many times -- and a core programming principle to work on is DRY (dont-repeat-yourself). Maybe you and I can jump on a zoom and work through a quick solution to refactor this code to work exactly the same, but with fewer lines and cleaner organization.

Overall, well done -- I didn't really have too much feedback, and as you continue on you'll solidify your skills. We should reconnect soon and chat as mentioned above!

**Comment by amdubay** [comment]
Taking a shot to progress toward a solution. Since my Python skills are dormant right now, my possible solution is written text, rather than written code. If you'd prefer to think through the solution on your own, quit reading here.

**For 1) The first cases are if the results are equal then it is a tie:** then as pointed out, line 152 can be changed to `user_Input == computer_Input` 153 and 154 will stay the same. 155 through 160 can be deleted.

**For 2) Winning cases:** Line 163, the first `if` logic for a winning result, can use the OR operator, all win comparisons (from line 166 and 169) can be included here. 164 and 165 would remain the same, and 166 - 171 can be deleted. For the loss logic, a simple `else` can be used, and will replace line 174. Line 175 and 176 would remain the same. 177-182 can be deleted.

**Comment by Spiggles8** [comment]
I appreciate the comments and will definitely be incorporating them in to the next revision. The next revision will begin once I get a solid foundation of Javascript and can migrate the game to a webpage.
